### ISSUE TITLE
Can a constraint be removed?

### ISSUE THREAD

**Issue by wjling** [layoutBox/FlexLayout#38]
Hello. I want to ask a question. I have an `UIImageView` as this:
```
imageView.flex.size(someSize)
```
If I don't want the size constraint in some conditions and use `imageView`'s intrinsic size, how can I remove the size constraints to the imageView?

**Comment by lucdion** [comment]
Hi @wjling, you're right! I'll add something today for these situations. Thanks

**Comment by lucdion** [comment]
@wjling see the latest release https://github.com/layoutBox/FlexLayout/releases/tag/1.1.8.
You can now `aspectRatio(nil)`

**Comment by lucdion** [comment]
Sorry @wjling, I have fixed something for aspectRatio, but you're issue was with size! 😌
I'll check that.

**Comment by wjling** [comment]
Happy to hear that this feature will be added. Thank you ! 👍

**Comment by lucdion** [comment]
Hi @wjling, can you test the latest release https://github.com/layoutBox/FlexLayout/releases/tag/1.2.0.

For your last comment, reset a margin is easy because the initial value is 0. But to reset other property as `size`, you must clear the property. Now giving `nil` as a parameter will do just that.

**Comment by wjling** [comment]
@lucdion  Sorry not response in time. I will try later!

**Comment by wjling** [comment]
@lucdion  I have simply tried `size(nil)` and `height(nil)` and it works for me! Others I have not tried yet.
