### ISSUE TITLE
How does UIImageView size work?

### ISSUE THREAD

**Issue by cielpy** [layoutBox/FlexLayout#88]
I have a question about UIImageView's size, look through the project there does not have UIImageView related special things, but when set an image to UIImageView, the UIImageView auto have a size, as Apple's document says, set image will not set the UIImageView's size but call sie `sizeToFit` method to set the size, so my question is how the UIImageView's size work in Yoga?

Addtionly, I have a situation that I want to add a button in a UIImageView object, but after added the button, the image resize to the button's size, not keep the image object's size, how to solve it? here is my code

```
flex.addItem().direction(.row).padding(10).define({ (flex) in
    let imageView = UIImageView()
    imageView.image = UIImage(named: "ui-icons_2e83ff_256x240")
    flex.addItem(imageView).define({ (flex) in
        flex.alignItems(.center)
        flex.justifyContent(.center)
        
        let button = UIButton()
        flex.addItem(button).backgroundColor(.red).define({ (flex) in
            flex.width(50)
            flex.height(50)
        })
    })
})

```

Thank you very much.

**Comment by egenvall** [comment]
I believe the documentation is not updated properly.

The ReadMe specifies the default shrink value as 0,  while the code documentation specifies the default shrink value as 1.

As a result, your imageview will shrink to fit its content I assume since you have not specified any specific size for your imageview.

An example with a Base UITableviewCell that exposes a contentContainer UIView for its subclasses (excluded irrelevant code)

The contentContainer will keep its size, regardless of the size of its eventual subviews because it will grow(1) to fill available space, but also shrink(1) to not overflow.

So the contentContainer can take any sub layout and expand or shrink vertically as needed, while maintaining the overall look.
``` 
Base class:
flex.addItem(container).direction(.row).define { container in
                container.addItem(iconView).size(40).shrink(0)
                container.addItem(contentContainer).marginLeft(16).padding(8).grow(1).shrink(1).define { contentCont in
                }
}

Subclass:
contentContainer.flex.define { content in
            content.addItem(container).define { cont in
                cont.addItem(textContainer).padding(padding).define { textCont in
                    textCont.addItem(myTextLabel).grow(1).shrink(1)
                }
            }    
}
```
Result:
![img_2664](https://user-images.githubusercontent.com/3669105/39747596-05284066-52ae-11e8-84db-c84f166408d9.JPG)

**Comment by cielpy** [comment]
Thanks @egenvall , since my situation is a little different to yours, I do not need the imageView grow, keep its size  and stay at the left of the container is my goal, if I set a size to the imageView, the effect is I want, so I think it's different between set a fixed size to the imageView vs set an image to the imageView and it get size auto, then I create this issue, want to the answer of the title question

@lucdion can you help me?

**Comment by egenvall** [comment]
Did you try .shrink(0)?

**Comment by cielpy** [comment]
@egenvall Yes, I have set the shrink to 0, but it also does'nt work well.

**Comment by cielpy** [comment]
As CSS's behavoir, if a div tag with no width set, it will have 0px width(be hidden), but if a Yoga items do not set a width, it will fill the container.

See https://codepen.io/cielpy/pen/rvvyYa

**Comment by cielpy** [comment]
With the Yoga playground, https://yogalayout.com/playground#eyJ3aWR0aCI6NTAwLCJoZWlnaHQiOjUwMCwicG9zaXRpb24iOnsidG9wIjpudWxsLCJyaWdodCI6bnVsbCwiYm90dG9tIjpudWxsLCJsZWZ0IjpudWxsfSwiY2hpbGRyZW4iOlt7IndpZHRoIjoiIiwiaGVpZ2h0IjoxMDAsInBvc2l0aW9uIjp7InRvcCI6bnVsbCwicmlnaHQiOm51bGwsImJvdHRvbSI6bnVsbCwibGVmdCI6bnVsbH0sIm1pbldpZHRoIjpudWxsLCJtYXhXaWR0aCI6bnVsbCwibWluSGVpZ2h0IjpudWxsLCJtYXhIZWlnaHQiOm51bGx9XSwibWluV2lkdGgiOm51bGwsIm1heFdpZHRoIjpudWxsLCJtaW5IZWlnaHQiOm51bGwsIm1heEhlaWdodCI6bnVsbH0=

not set value to the width value, the item will be fixed to it's content size
